### ISSUE TITLE
Tracking: Memory Card Game

### ISSUE THREAD

**Issue by forvais** [FoRVaiS/2537a1#181]
Issues to track:
- [ ] Display game menu on page load
- [ ] Generate board and solutions
- [ ] Display cards in a n by m grid
- [ ] Implement card selections
- [ ] Verify solutions after selecting two cards
 

- [ ] Card has a front and back
- [ ] Lock card selections while animations are still playing
- [ ] Create a timer that can be adjusted by a difficulty setting
